mysql:
    host: localhost
    user: root
    passwd:
    db: tweet
twitter:
    consumer_key : "SGxQUNWg7MM69iwxMe9WeICQP"
    consumer_secret : "I844RT34PMOenus0assWA67t0nKXwjwcNERlD8LNzCPM6rh7Yt"
    access_token : "42856552-fr0YbHWOk6VJbeayjQJrhf3Rf6AvEChfVhtVF9HT1"
    access_token_secret : "up0DNinFpWOo3GYwDig5klbB0G1F9DptDmlikWqXb24fo"
